name: construction_site
description: flutter web construction site

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  universal_html: ^1.1.4
  carousel_slider: ^1.3.0
  simple_animations: ^1.3.3
  build_config: ^0.4.1+1
  firebase: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

analyzer:
  exclude:
    - lib/create_directory.dart


